name: Inject Telegram Details into APK

on:
  workflow_dispatch:
    inputs:
      apk_url:
        description: 'Direct URL to base APK file (Sms Eye 2 APK)'
        required: true
      app_url:
        description: 'URL to display on app startup (url.txt)'
        required: true

jobs:
  patch-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y default-jdk wget zipalign
        wget https://github.com/iBotPeaches/Apktool/releases/latest/download/apktool_2.9.3.jar -O apktool.jar

    - name: Download Base APK
      run: |
        wget "${{ github.event.inputs.apk_url }}" -O base.apk

    - name: Decompile APK
      run: |
        java -jar apktool.jar d base.apk -o decoded_apk --force

    - name: Inject Telegram Details into Assets
      run: |
        echo "${{ secrets.BOT_TOKEN }}" > decoded_apk/assets/token.txt
        echo "${{ secrets.CHAT_ID }}" > decoded_apk/assets/id.txt
        echo "${{ github.event.inputs.app_url }}" > decoded_apk/assets/url.txt

    - name: Rebuild APK
      run: |
        java -jar apktool.jar b decoded_apk -o unsigned.apk

    - name: Sign APK
      run: |
        keytool -genkey -v -keystore keystore.jks -storepass password -alias key0 -keypass password \
          -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=SmsEye"
        jarsigner -verbose -keystore keystore.jks -storepass password -keypass password unsigned.apk key0
        mv unsigned.apk SmsEye_Modified.apk

    - name: Upload Final APK
      uses: actions/upload-artifact@v4
      with:
        name: Patched-SmsEye-APK
        path: SmsEye_Modified.apk
